Removed unused field
system/core/fs_mgr/libsnapshot/snapuserd/user-space-merge/handler_manager.h:149:10: error: private field 'perform_verification_' is not used [-Werror,-Wunused-private-field]
  149 |     bool perform_verification_ = true;
      |          ^
1 error generated.

Test: presubmit
Change-Id: I862db34623e3489c05aa614e8a2895bcead785cb